//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "collection_offer")]
pub struct Model {
    pub tx_hash: String,
    pub created_date: DateTimeWithTimeZone,
    pub buyer_address: String,
    pub collection_address: String,
    #[sea_orm(column_type = "Decimal(Some((90, 2)))")]
    pub price: Decimal,
    pub quantity: i32,
    pub start_date: DateTimeWithTimeZone,
    pub end_date: DateTimeWithTimeZone,
    pub denom: String,
    pub current_quantity: i32,
    #[sea_orm(primary_key)]
    pub id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
