//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "collection_snapshot")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub collection_address: String,
    pub date: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Decimal(Some((90, 2)))")]
    pub floor: Decimal,
    #[sea_orm(column_type = "Decimal(Some((90, 2)))")]
    pub volume_of_24h: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
