//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "collection")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub address: String,
    pub name: String,
    pub symbol: String,
    pub image: Option<String>,
    pub banner: Option<String>,
    pub description: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((90, 2)))", nullable)]
    pub royalty: Option<Decimal>,
    pub supply: i32,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub socials: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::nft::Entity")]
    Nft,
    #[sea_orm(has_many = "super::transaction::Entity")]
    Transaction,
}

impl Related<super::nft::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Nft.def()
    }
}

impl Related<super::transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transaction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
