//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "mint_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub collection_address: String,
    pub group_name: String,
    pub recipient: String,
    #[sea_orm(column_type = "Text")]
    pub token_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
