//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "nft_bidding")]
pub struct Model {
    pub tx_hash: String,
    pub created_date: DateTimeWithTimeZone,
    pub buyer_address: String,
    #[sea_orm(column_type = "Decimal(Some((90, 2)))")]
    pub price: Decimal,
    pub denom: String,
    pub listing_id: i32,
    #[sea_orm(primary_key)]
    pub id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::listing_nft::Entity",
        from = "Column::ListingId",
        to = "super::listing_nft::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ListingNft,
}

impl Related<super::listing_nft::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ListingNft.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
