//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use super::sea_orm_active_enums::LoyaltyPointKind;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user_loyalty_point")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub wallet_address: String,
    pub date: DateTimeWithTimeZone,
    pub kind: LoyaltyPointKind,
    pub point: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
